### ISSUE TITLE
experiment.pyの実行エラー

### ISSUE THREAD

**Issue by kento1109** [kento1109/RCGAN#1]
・sin_wave.npzだとうまくいくのですが、mnist1.npz（rotMNIST.zipを解凍して作成しました）だとエラーが出ます。

```
Traceback (most recent call last):
  File "experiment.py", line 56, in <module>
    main()
  File "experiment.py", line 50, in main
    y_eval)
  File "/data/kojima/RCGAN/model.py", line 252, in train
    mmd2, that_np = self.my_mmd.calc_mmd(eval_x, eval_gx)
  File "/data/kojima/RCGAN/model.py", line 43, in calc_mmd
    self.sess)
  File "/data/kojima/RCGAN/mmd.py", line 255, in sigma_optimization
    dic_tf_sigma['eval_sample_PH']: eval_eval_sample})
  File "/home/kojima/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/tensorflow/python/client/session.py",
line 877, in run
    run_metadata_ptr)
  File "/home/kojima/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/tensorflow/python/client/session.py",
line 1076, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (0,) for Tensor
'Placeholder_2:0', which has shape '(0, 30, 784)'
```

**Comment by kento1109** [comment]
rotMNISTデータはサイズが大きいので、少ないサンプル数しかgithub上に置けない。
その場合はMMD計算時に数が少なすぎてエラーになるよう（最低バッチ数×10以上）が必要。

ローカルの環境で  `build_rotMNIST.py`  を実行して、rotMNISTデータを生成頂くのがよい。
